---
- name: installation de l'appli flaskr
  hosts: client
  remote_user: root
  
  vars:
    packages:
      - unzip
      - python-minimal
      - python3 
      - python-pip
      - python-apt
  
  tasks: 
    - name: telechargement de flaskr
      get_url: 
        url: https://github.com/silshack/flaskr/archive/master.zip
        dest: /tmp/
        mode: '0440'
   
    - name: installation des outils
      apt: 
        pkg: "{{ packages }}"  

    - name: creation du rep de l application
      file:
        path: /app/flaskr.botify.com/
        state: directory
        mode: '0755'

    - name: dezip de flaskr
      unarchive:
        src: /tmp/flaskr-master.zip
        dest: /tmp/
        remote_src: yes
    - name: copie des fichiers 
      copy:
        src: /tmp/flaskr-master/
        dest: /app/flaskr.botify.com/
        remote_src: yes
      
    - name: copie du fichier pour creer le service
      copy:
        src: ./flaskr.service
        dest: /etc/systemd/system/
        mode: '0755'
        remote_src: no  

    - name: creation du lien symbolic pour le demarage du service au boot de la machine
      file:
        src: /etc/systemd/system/flaskr.service
        dest: /etc/rc5.d/S10flaskr
        owner: root
        group: root
        state: link

    - name: enable flaskr service 
      systemd:
        name: flaskr
        enabled: yes
        masked: no

    - pip:
       name: Flask 
...
